services:
  twitter_react_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: twitter_react_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - backend
    volumes:
      - ./client:/app/client
    command: bash -c "npm run dev"
  node_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./server:/app/server
    command: bash -c "npm run dev"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: twitter_clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
