services:
  twitter_react_app:
    container_name: twitter_react_app
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_PROTOCOL=http
      - API_HOST_NAME=localhost
      - API_PORT=3001
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /dev/null:/app/client/.env.development
    command: bash -c "npm run dev"
  node_app:
    container_name: node_app
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres_db
      - DB_NAME=twitter_clone_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - JWT_SECRET=secret
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECRET=secret
      - COOKIE_MAX_AGE=604800000
      - CLIENT_HOST=localhost
      - CLIENT_PORT=3000
      - SERVER_PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - /dev/null:/app/server/.env.development
      - /dev/null:/app/server/.env.test
    command: bash -c "npm run dev"
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: twitter_clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
