services:
  twitter_react_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: twitter_react_app
    container_name: twitter_react_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - backend
    volumes:
      - .:/app/server
      - /app/client/node_modules
    command: bash -c "npm run client"
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node_app
    container_name: node_app
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/app/client
      - /app/server/node_modules
    command: bash -c "npm run server"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: twitter_clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
